### ISSUE TITLE
主界面更新弹窗显示后，在没有关闭弹窗的时候点击返回键退出App崩溃

### ISSUE THREAD

**Issue by 13253863229** [WVector/AppUpdate#147]
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.vector.update_app.UpdateAppBean)
        at android.os.Parcel.writeSerializable(Parcel.java:1842)
        at android.os.Parcel.writeValue(Parcel.java:1789)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:931)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1588)
        at android.os.Bundle.writeToParcel(Bundle.java:1253)
        at android.os.Parcel.writeBundle(Parcel.java:1000)
        at androidx.fragment.app.FragmentState.writeToParcel(FragmentState.java:125)
        at android.os.Parcel.writeTypedObject(Parcel.java:1643)
        at android.os.Parcel.writeTypedList(Parcel.java:1522)
        at android.os.Parcel.writeTypedList(Parcel.java:1479)
        at androidx.fragment.app.FragmentManagerState.writeToParcel(FragmentManagerState.java:58)
        at android.os.Parcel.writeParcelable(Parcel.java:1810)
        at android.os.Parcel.writeValue(Parcel.java:1716)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:931)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1588)
        at android.os.Bundle.writeToParcel(Bundle.java:1253)
        at android.os.Parcel.writeBundle(Parcel.java:1000)
        at android.os.Parcel.writeValue(Parcel.java:1707)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:931)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1588)
        at android.os.Bundle.writeToParcel(Bundle.java:1253)
        at android.os.Parcel.writeBundle(Parcel.java:1000)
        at android.os.Parcel.writeValue(Parcel.java:1707)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:931)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1588)
        at android.os.Bundle.writeToParcel(Bundle.java:1253)
        at android.app.IActivityTaskManager$Stub$Proxy.activityStopped(IActivityTaskManager.java:4562)
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:145)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8668)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

**Comment by ZhiQiangCoding** [comment]
大佬问题解决么，我们也遇到了这个问题

**Comment by 13253863229** [comment]
> 大佬问题解决么，我们也遇到了这个问题

没有，只能改源码了
