### ISSUE TITLE
DEMO报错

### ISSUE THREAD

**Issue by mengxiabing** [WVector/AppUpdate#25]
从这里下载的DEMO，在AS里可以编译运行，但是把编译过后的APK安装包手动放到手机里安装就会报错，报错如下：
08-24 09:30:46.441 9399-9399/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.vector.appupdatedemo, PID: 9399
                                                 java.lang.RuntimeException: Unable to instantiate application com.vector.appupdatedemo.App: java.lang.ClassNotFoundException: Didn't find class "com.vector.appupdatedemo.App" on path: DexPathList[[zip file "/data/app/com.vector.appupdatedemo-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                     at android.app.LoadedApk.makeApplication(LoadedApk.java:563)
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4576)
                                                     at android.app.ActivityThread.access$1500(ActivityThread.java:148)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1353)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:135)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5310)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.vector.appupdatedemo.App" on path: DexPathList[[zip file "/data/app/com.vector.appupdatedemo-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                     at android.app.Instrumentation.newApplication(Instrumentation.java:1002)
                                                     at android.app.LoadedApk.makeApplication(LoadedApk.java:558)
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4576) 
                                                     at android.app.ActivityThread.access$1500(ActivityThread.java:148) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1353) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:135) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5310) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696) 
                                                 	Suppressed: java.lang.ClassNotFoundException: com.vector.appupdatedemo.App
                                                     at java.lang.Class.classForName(Native Method)
                                                     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                     		... 13 more
                                                  Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by WVector** [comment]
重新试一下

**Comment by mengxiabing** [comment]
感谢回复，后来检查到这个问题是开启了增量编译引起的，已经解决。
