### ISSUE TITLE
java.lang.IllegalArgumentException: unexpected url: www.xxxx.com/xs/xxx/app/xxx_Android_01.01.40.apk

### ISSUE THREAD

**Issue by shiwobuhaoma** [WVector/AppUpdate#36]
url中存在下划线，好像就会报这个异常。
 at okhttp3.Request$Builder.url(Request.java:143)
at com.zhy.http.okhttp.request.OkHttpRequest.initBuilder(OkHttpRequest.java:49)
at com.zhy.http.okhttp.request.OkHttpRequest.<init>(OkHttpRequest.java:39)
at com.zhy.http.okhttp.request.GetRequest.<init>(GetRequest.java:15)
at com.zhy.http.okhttp.builder.GetBuilder.build(GetBuilder.java:31)
at com.mengtai.athome.common.utils.UpdateAppHttpUtil.download(UpdateAppHttpUtil.java:97)

**Comment by WVector** [comment]
url没有http://
