### ISSUE TITLE
我导入发生了错误

### ISSUE THREAD

**Issue by android-cui** [WVector/AppUpdate#5]
Process: tsinghua.com.villageassistantclick, PID: 13145
                                                                                    java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                                                        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
                                                                                        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                                                                                        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                        at java.lang.Thread.run(Thread.java:841)
                                                                                     Caused by: java.lang.NoClassDefFoundError: okhttp3.internal.http.HttpEngine
                                                                                        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:219)
                                                                                        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                                        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                                        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
                                                                                        at okhttp3.RealCall.execute(RealCall.java:60)
                                                                                        at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
                                                                                        at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:171)
                                                                                        at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80)
                                                                                        at rx.Subscriber.setProducer(Subscriber.java:209)
                                                                                        at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76)
                                                                                        at rx.Subscriber.setProducer(Subscriber.java:205)
                                                                                        at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
                                                                                        at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
                                                                                        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
                                                                                        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                                                        at rx.Observable.unsafeSubscribe(Observable.java:8666)
                                                                                        at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
                                                                                        at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:220)
                                                                                        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                                        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152) 
                                                                                        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265) 
                                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                        at java.lang.Thread.run(Thread.java:841)

**Comment by WVector** [comment]
你导入的整个项目？报错了
