### ISSUE TITLE
动态申请读写本地存储权限时出错

### ISSUE THREAD

**Issue by Chihiro23333** [WVector/AppUpdate#89]
弹出对话框,点击升级时,弹出权限申请对话框奔溃,测试机型小米4 android 6.0

06-22 10:21:14.046 25428-25428/net.wkzj.wkzjapp.student E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.wkzj.wkzjapp.student, PID: 25428
    java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.vector.update_app.UpdateAppBean)
        at android.os.Parcel.writeSerializable(Parcel.java:1468)
        at android.os.Parcel.writeValue(Parcel.java:1416)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:686)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1376)
        at android.os.Bundle.writeToParcel(Bundle.java:1079)
        at android.os.Parcel.writeBundle(Parcel.java:711)
        at android.support.v4.app.FragmentState.writeToParcel(FragmentState.java:120)
        at android.os.Parcel.writeTypedArray(Parcel.java:1254)
        at android.support.v4.app.FragmentManagerState.writeToParcel(FragmentManager.java:617)
        at android.os.Parcel.writeParcelable(Parcel.java:1437)
        at android.os.Parcel.writeValue(Parcel.java:1343)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:686)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1376)
        at android.os.Bundle.writeToParcel(Bundle.java:1079)
        at android.os.Parcel.writeBundle(Parcel.java:711)
        at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3216)
        at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3496)
        at android.os.Handler.handleCallback(Handler.java:742)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
     Caused by: java.io.NotSerializableException: net.wkzj.wkzjapp.ui.main.activity.MainActivity
        at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1344)
        at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
        at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
        at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
        at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
        at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
        at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
        at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
        at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
        at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
        at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
        at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
        at android.os.Parcel.writeSerializable(Parcel.java:1463)
        at android.os.Parcel.writeValue(Parcel.java:1416) 
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:686) 
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1376) 
        at android.os.Bundle.writeToParcel(Bundle.java:1079) 
        at android.os.Parcel.writeBundle(Parcel.java:711) 
        at android.support.v4.app.FragmentState.writeToParcel(FragmentState.java:120) 
        at android.os.Parcel.writeTypedArray(Parcel.java:1254) 
        at android.support.v4.app.FragmentManagerState.writeToParcel(FragmentManager.java:617) 
        at android.os.Parcel.writeParcelable(Parcel.java:1437) 
        at android.os.Parcel.writeValue(Parcel.java:1343) 
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:686) 
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1376) 
        at android.os.Bundle.writeToParcel(Bundle.java:1079) 
        at android.os.Parcel.writeBundle(Parcel.java:711) 
        at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3216) 
        at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3496) 
        at android.os.Handler.handleCallback(Handler.java:742) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:157) 
        at android.app.ActivityThread.main(ActivityThread.java:5653) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)

**Comment by protectedMan** [comment]
什么原因呢，我也遇到这个问题

**Comment by hardlove** [comment]
遇到同样问题，下载安装包完成后，就crash了。

 java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.vector.update_app.UpdateAppBean)
                                                                                    at android.os.Parcel.writeSerializable(Parcel.java:1714)
                                                                                    at android.os.Parcel.writeValue(Parcel.java:1662)
                                                                                    at android.os.Parcel.writeArrayMapInternal(Parcel.java:875)
                                                                                    at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1583)
                                                                                    at android.os.Bundle.writeToParcel(Bundle.java:1233)
                                                                                    at android.os.Parcel.writeBundle(Parcel.java:915)
                                                                                    at android.support.v4.app.FragmentState.writeToParcel(FragmentState.java:124)
                                                                                    at android.os.Parcel.writeTypedObject(Parcel.java:1516)
                                                                                    at android.os.Parcel.writeTypedArray(Parcel.java:1497)
                                                                                    at android.support.v4.app.FragmentManagerState.writeToParcel(FragmentManager.java:639)
                                                                                    at android.os.Parcel.writeParcelable(Parcel.java:1683)
                                                                                    at android.os.Parcel.writeValue(Parcel.java:1589)
                                                                                    at android.os.Parcel.writeArrayMapInternal(Parcel.java:875)
                                                                                    at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1583)
                                                                                    at android.os.Bundle.writeToParcel(Bundle.java:1233)
                                                                                    at android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:3986)
                                                                                    at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:144)
                                                                                    at android.os.Handler.handleCallback(Handler.java:907)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                    at android.os.Looper.loop(Looper.java:216)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:7625)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
                                                                                 Caused by: java.io.NotSerializableException: com.android.lexin.model.utils.OkGoUpdateHttpUtil$4
                                                                                    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
                                                                                    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
                                                                                    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
                                                                                    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
                                                                                    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
                                                                                    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
                                                                                    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
                                                                                    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
                                                                                    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
                                                                                    at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
                                                                                    at android.os.Parcel.writeSerializable(Parcel.java:1709)
                                                                                    at android.os.Parcel.writeValue(Parcel.java:1662) 
                                                                                    at android.os.Parcel.writeArrayMapInternal(Parcel.java:875) 
                                                                                    at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1583) 
                                                                                    at android.os.Bundle.writeToParcel(Bundle.java:1233) 
                                                                                    at android.os.Parcel.writeBundle(Parcel.java:915) 
                                                                                    at android.support.v4.app.FragmentState.writeToParcel(FragmentState.java:124) 
                                                                                    at android.os.Parcel.writeTypedObject(Parcel.java:1516) 
                                                                                    at android.os.Parcel.writeTypedArray(Parcel.java:1497) 
                                                                                    at android.support.v4.app.FragmentManagerState.writeToParcel(FragmentManager.java:639) 
                                                                                    at android.os.Parcel.writeParcelable(Parcel.java:1683) 
                                                                                    at android.os.Parcel.writeValue(Parcel.java:1589) 
                                                                                    at android.os.Parcel.writeArrayMapInternal(Parcel.java:875) 
                                                                                    at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1583) 
                                                                                    at android.os.Bundle.writeToParcel(Bundle.java:1233) 
                                                                                    at android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:3986) 
                                                                                    at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:144) 
                                                                                    at android.os.Handler.handleCallback(Handler.java:907) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                                    at android.os.Looper.loop(Looper.java:216) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:7625) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
