### ISSUE TITLE
更新弹框出来了，但是点击升级，就会崩溃。报错：java.lang.NoSuchMethodError: No direct method

### ISSUE THREAD

**Issue by yecaler** [WVector/AppUpdate#91]
当点击升级，会出现如下异常：

java.lang.NoSuchMethodError: No direct method <init>(Landroid/content/Context;Ljava/lang/String;)V in class Landroid/support/v4/app/NotificationCompat$Builder; or its super classes (declaration of 'android.support.v4.app.NotificationCompat$Builder' appears in /data/app/base-2/base.apk:classes45.dex)
        at com.vector.update_app.service.DownloadService.setUpNotification(DownloadService.java:109)
        at com.vector.update_app.service.DownloadService.access$200(DownloadService.java:29)
        at com.vector.update_app.service.DownloadService$FileDownloadCallBack.onBefore(DownloadService.java:243)
        at com.jach.base.http.UpdateAppHttpUtil$3.onBefore(UpdateAppHttpUtil.java:109)
        at com.zhy.http.okhttp.request.RequestCall.execute(RequestCall.java:88)
        at com.jach.base.http.UpdateAppHttpUtil.download(UpdateAppHttpUtil.java:89)
        at com.vector.update_app.service.DownloadService.startDownload(DownloadService.java:142)
        at com.vector.update_app.service.DownloadService.access$000(DownloadService.java:29)
        at com.vector.update_app.service.DownloadService$DownloadBinder.start(DownloadService.java:223)
        at com.vector.update_app.UpdateDialogFragment.startDownloadApp(UpdateDialogFragment.java:383)
        at com.vector.update_app.UpdateDialogFragment.access$000(UpdateDialogFragment.java:49)
        at com.vector.update_app.UpdateDialogFragment$1.onServiceConnected(UpdateDialogFragment.java:65)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1258)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1275)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:5610)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)

![default](https://user-images.githubusercontent.com/25024969/42270474-8d4cec80-7fb3-11e8-8802-bea2600aaa7e.png)

提示为这个地方出错，请教大神如何解决！

**Comment by yecaler** [comment]
已解决，因为v4包和v7包版本太低了。

**Comment by chenkexu** [comment]
现在还是不行啊

**Comment by zhongdevin** [comment]
> 已解决，因为v4包和v7包版本太低了。

没有解决吧，我的包是28的了
